### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by Noobforlife** [janfriedli/akut-shift-planner#96]
Hi.

Ive put put Akut-shift-planner on my server and it comes up as German. How can i change it to english?

i can see the xlf file for english but have no idea on how to select it. is there also a admin to control the site

thank you

**Comment by fribim** [comment]
Hi @Noobforlife 

You have to set the `default_locale: de` to `en`
https://github.com/fribim/akut-shift-planner/blob/develop/app/config/config.yml#L24 

Actually there isn't an admin area right now.

Hope that helps

**Comment by Noobforlife** [comment]
Hi @fribim 

thank you for the quick response. 

I changed it to english and it still shows German.

**Comment by fribim** [comment]
Try to delete the cache that's usually the most common problem:
`php bin/console cache:clear`

**Comment by Noobforlife** [comment]
strange @fribim . it shows

```
php bin/console cache:clear

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.   
```

**Comment by fribim** [comment]
could you please show me your `config.yml`?
Did you do a hard reload in your browser?

I just tried it out on my env and that caused no problems.

**Comment by Noobforlife** [comment]
sure thing. yup also used different browsers incase it was browser cache.

```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: en
    translator: { fallbacks: [en] }
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/form_errors.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: ssl
    port: 465
    auth_mode: login
    spool:
        type: file
        path: '%kernel.project_dir%/app/spool'

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

knp_paginator:
    page_range:                 10          # default page range used in pagination control
    default_options:
        page_name:              page       # page query parameter name
        sort_field_name:        sort       # sort field query parameter name
        sort_direction_name:    direction  # sort direction query parameter name
        distinct:               true       # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v4_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    resetting:
            email:
                from_email:
                    address:        no-reply@schicht-plan.ch
                    sender_name:    Password Reset Schicht-Plan.ch
```

**Comment by fribim** [comment]
Hmm strange the config file looks good. 
I can't reproduce your issue...

I assume you're using the built in dev server?  
` php bin/console server:start`

**Comment by Noobforlife** [comment]
yes. using `php bin/console server:start` aswell :(

**Comment by fribim** [comment]
what happens if you remove `default_locale: en` completely and restart the server?

**Comment by Noobforlife** [comment]
crazy stuff. still the exact same. restart apache or the actual server?

**Comment by fribim** [comment]
You don't need an apache server if you are using the built in server...

1. `php bin/console server:stop`
2. `php bin/console server:start`

After that you can point your browser to: http://localhost:8000/

**Comment by Noobforlife** [comment]
no luck @fribim :/

**Comment by fribim** [comment]
Damn I have no other idea. Well maybe a fresh clone and configuring it before starting the server might help... make sure you stopped the old server beforehand.

**Comment by Noobforlife** [comment]
okay success. php bin/console cache:warmup --env=prod did the trick

however on creating a new template something didnt work well

![image](https://user-images.githubusercontent.com/15904515/32630055-87d396d2-c59b-11e7-8ced-fd7327a56d76.png)


is the date etc suppose to open a calendar?

**Comment by fribim** [comment]
Jup it should open a date/time select dialog.
Seems like the corresponding JS has not initialised/loaded.
<img width="443" alt="screen shot 2017-11-09 at 22 20 20" src="https://user-images.githubusercontent.com/7932500/32630238-36d86fa4-c59c-11e7-92e9-0e782927763f.png">

**Comment by Noobforlife** [comment]
how can i initialise or load it? im awfully new to php

**Comment by fribim** [comment]
Does it load the mentioned js files?
<img width="643" alt="screen shot 2017-11-09 at 22 29 03" src="https://user-images.githubusercontent.com/7932500/32630593-804f73ca-c59d-11e7-8ebc-789dad247c2f.png">

**Comment by Noobforlife** [comment]
GG. errror 500

`PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/var/www/akut-shift-planner/var/cache/prod)\n in /var/www/akut-shift`

**Comment by Noobforlife** [comment]
nevermind. got the site back. but

![image](https://user-images.githubusercontent.com/15904515/32630892-9c4ea680-c59e-11e7-8ae9-52e5314f4fdd.png)

**Comment by fribim** [comment]
Are you mixing the built in server and an apache server? That might cause some trouble...
What probably works is cloning again in another directory (not under /var/www), changing the config and serving the page with the server:start command

**Comment by Noobforlife** [comment]
i shall sleep on it and try tomorrow. and give u an update.

thank you for all the help

**Comment by Noobforlife** [comment]
still no luck. been trying apache and no luck. still get the same issue

**Comment by janfriedli** [comment]
Hmm one last try: 

Run these: 

```bash
php bin/symfony_requirements
php bin/console cache:clear --env=prod --no-debug --no-warmup
php bin/console cache:warmup --env=prod
php bin/console assetic:dump --env=prod --no-debug --env=prod
php bin/console doctrine:schema:update --force --env=prod
```

That should fix the missing JS deps. 
You can find these commands in the post-deploy script.... 
You can adjust the env param to `dev` if you want to

**Comment by Noobforlife** [comment]
that worked. ```php bin/console assetic:dump --env=prod --no-debug --env=prod``` was the culprit

**Comment by janfriedli** [comment]
:+1:
