### ISSUE TITLE
Feature Request: Monthly View

### ISSUE THREAD

**Issue by Noobforlife** [janfriedli/akut-shift-planner#97]
Hi. 

My office is open 24/7. and having a monthly view of who works what shift would be great.

having an admin assign shifts to each member would be great. having a super user able to create and assign shifts to a member.

![image](https://user-images.githubusercontent.com/15904515/32772385-fd49a3ec-c925-11e7-9f3c-1f1ef9acd20e.png)

**Comment by janfriedli** [comment]
Hi @Noobforlife  
This shift planner has been designed for single events... 
At the moment I don't have the time to implement such big features but feel free to submit a Pull Request
